name: Build, Test, and Publish ReswPlus

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Runs only when a tag like v1.0.0 is pushed
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Build Solution
        run: dotnet build src/ReswPlus.SourceGenerator/ReswPlus.SourceGenerator.csproj --configuration Release

      - name: Run Unit Tests
        run: dotnet test tests/ReswPlusUnitTests/ReswPlusUnitTests.csproj --configuration Release --verbosity normal

      - name: Extract Version from NugetPackage.props
        id: extract_version
        run: |
          [xml]$csproj = Get-Content "nuget\Starpine.ReswPlus.SourceGenerator.NugetPackage.props"
          $version = "$($csproj.Project.PropertyGroup.FileVersion)-$(Get-Date -Format "yyyyMMddHHmm")+${{ github.sha }}"
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Pack Snapshot NuGet Package
        run: dotnet pack src/ReswPlus.SourceGenerator/ReswPlus.SourceGenerator.csproj --configuration Release --output nupkg -p:PackageId=Starpine.ReswPlus -p:FileVersion=${{ steps.extract_version.outputs.version }}

      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ReswPlus-NuGet-Packages
          path: "**/nupkg/*.nupkg"

      - name: Push NuGet Package
        if: github.event_name == 'push'
        run: dotnet nuget push "**/nupkg/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" -s "https://api.nuget.org/v3/index.json"
